### ISSUE TITLE
Implement ideas showcased by the now no longer publicly available Think Suite toolkit?

### ISSUE THREAD

**Issue by no-identd** [twschiller/open-synthesis#161]
See http://web.archive.org/web/20150826111836/http://globalytica.com/thinksuite.html, http://www.pherson.org/ach/, https://shop.globalytica.com/collections/learning-aids/products/th-nk-suite-license and http://www.globalytica.com/wp-content/uploads/2016/03/Strategic-Foresight_Nine-Techniques.pdf.

**Comment by twschiller** [comment]
Thanks for the links. Here are some thoughts on ThinkSuite. I'll address the Foresight Nine techniques in a separate comment. Those are more related to some other tools I want to work on in the future

- Hypothesis Generation: I suspect ThinkSuite's approach has more benefit when you're working through ACH with a small group. When working in the open, we get the benefit of crowdsourcing from diverse viewpoints (what crowdsourcing is good at). That being said, the ThinkSuite approach would 1) create a cleaner set of hypotheses since the results are mutually exclusive, and 2) lead to more systematic coverage of the hypotheses space. I probably won't prioritize this for now

- ACH board: generally the same as what's already implemented. Although they make the credibility indicator more prominent. Not sure what "Assumptions" and "Credibility Justification" fields are in the notes column. If someone can get a hand on the tool (or more screenshots), would be interesting to see what it allows notes to be attached to

- Indicators Validator: from what I can tell, generally what we already have implemented. Currently the evidence is by default sorted by diagnosticity. For large boards, we'll probably want hide non-diagnostic evidence by default

**Comment by no-identd** [comment]
...you wanted to say something about Foresight Nine?

**Comment by no-identd** [comment]
Ah. Seems the link died. Here, an archive copy:
https://web.archive.org/web/20161109230503/http://www.globalytica.com/wp-content/uploads/2016/03/Strategic-Foresight_Nine-Techniques.pdf

**Comment by twschiller** [comment]
@no-identd, thanks for the link. Added it to the reading list on the wiki: https://github.com/twschiller/open-synthesis/wiki/Reading-List

Think there's some good ideas/frameworks we can draw on. Focus for this project will be figuring out best way to drive engagement. Think content on ACH is more important that framework coverage
